In [11]:
pip install torch

     -------------------------------------- 172.4/172.4 MB 6.6 MB/s eta 0:00:00
     ---------------------------------------- 5.7/5.7 MB 11.8 MB/s eta 0:00:00
     ------------------------------------- 536.2/536.2 KB 11.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
You should consider upgrading via the 'c:\Users\LG\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [50]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\LG\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [23]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\LG\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [51]:
import torch
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize
import gensim
from gensim.models import Word2Vec
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings(action='ignore')
import math
import scipy
from scipy.special import softmax

### 위치 인코딩 코드 예시

In [6]:
# d_model = 512
def positional_encoding(pos, pe) : 
    for i in range(0, 512, 2) : 
        pe[0][i] = math.sin(pos / (1000 ** ((2*i)/512)))
        pc[0][i] = (y[0][i]*math.sqrt(d_model)) + pe[0][i]

        pe[0][i+1] = math.cos(pos / (1000 ** ((2*i)/512)))
        pc[0][i+1] = (y[0][i+1]*math.sqrt(d_model)) + pe[0][i+1]
    return pe

### 입력 임베딩

In [14]:
# prints outputs if set to 1, default=0
dprint=0

sample = open('./data/text.txt', 'r')
s = sample.read()

# escape 문자 전처리하기
f = s.replace('\n', ' ')

data = []

# 문장 parsing
for i in sent_tokenize(f) : 
    temp = []
    # 문장을 단어로 tokenize하기
    for j in word_tokenize(i) : 
        temp.append(j.lower())
    data.append(temp)

# Creating Skip Gram model 
#model2 = gensim.models.Word2Vec(data, min_count = 1, size = 512,window = 5, sg = 1) 
#model = Word2Vec(sentences=common_texts, vector_size=100, window=5, min_count=1, workers=4)
model2 = gensim.models.Word2Vec(data, min_count=1, vector_size=512, window=5, sg=1)

# 1-The 2-black 3-cat 4-sat 5-on 6-the 7-couch 8-and 9-the 10-brown 11-dog 12-slept 13-on 14-the 15-rug.
word1='black'
word2='brown'
pos1=2
pos2=10
a = model2.wv[word1]
b = model2.wv[word2]

if dprint == 1 : 
    print(a)

# 코사인 유사도 계산
dot = np.dot(a, b)
norma = np.linalg.norm(a)
normb = np.linalg.norm(b)
cos = dot / (norma * normb)

aa = a.reshape(1, 512)
ba = b.reshape(1, 512)
cos_lib = cosine_similarity(aa, bb)

In [15]:
print('black=', aa)

black= [[-0.06562666 -0.05351061 -0.00367221  0.06062042 -0.00825019  0.03129761
   0.04094656 -0.0424781   0.02367186 -0.00713359  0.02598262 -0.00719514
  -0.00289508 -0.00929283 -0.02900256 -0.02728165  0.03671551  0.07769296
  -0.07263705 -0.04485688  0.04485427 -0.03313118  0.10418661  0.02434326
  -0.02192764  0.00515197  0.03559645  0.03915194 -0.00977631 -0.10745304
  -0.01346472  0.03907425  0.02671207 -0.01067893 -0.00663914  0.00800821
   0.04495844 -0.05629048 -0.00073539 -0.01153074 -0.08249988  0.08180326
  -0.07897271 -0.04355659  0.05569189  0.01140373 -0.00112619  0.05680707
   0.0901883   0.09711304 -0.05737246  0.04957561  0.05798693  0.10256263
  -0.06556486 -0.00416581  0.0521906  -0.04471232  0.0099958   0.05621516
   0.0546289  -0.03182605 -0.00359466  0.02774827  0.0114772  -0.0040597
  -0.03139506  0.03170055 -0.02370839 -0.02381434 -0.00193404 -0.05785833
   0.01020833 -0.07639617  0.04624535 -0.0022714   0.05824702  0.02433532
   0.00560469  0.08525062  0.066

In [16]:
print('brown=', ba)

brown= [[-6.57081455e-02 -5.01695760e-02 -4.24045091e-03  5.99747598e-02
  -9.01406258e-03  2.92453878e-02  4.18420322e-02 -4.35429439e-02
   2.37510670e-02 -9.04465280e-03  2.84185782e-02 -7.19429273e-03
  -4.42801602e-03 -1.06724668e-02 -2.83944234e-02 -2.53625400e-02
   3.53969559e-02  7.37613589e-02 -7.27134943e-02 -4.62855585e-02
   4.38115895e-02 -3.52960452e-02  1.03932567e-01  2.39946935e-02
  -2.42137276e-02  2.45875167e-03  3.55703421e-02  3.98810096e-02
  -1.08563043e-02 -1.07635453e-01 -1.17596304e-02  3.61270681e-02
   2.52631642e-02 -1.09552043e-02 -7.87405297e-03  8.60247668e-03
   4.54603620e-02 -5.25691845e-02  2.28873012e-03 -1.21171428e-02
  -8.04095492e-02  8.15203786e-02 -7.90144205e-02 -4.27241363e-02
   5.67385741e-02  1.36796879e-02  2.37557408e-03  5.67543842e-02
   8.81103799e-02  9.94643867e-02 -5.82530424e-02  4.76997159e-02
   5.46795316e-02  1.01145864e-01 -6.51628822e-02 -4.40877676e-03
   5.53923734e-02 -4.61991653e-02  7.01655261e-03  5.50723262e-02
   

In [17]:
# 코사인 유사도(초기)
print('cosine_similarity(black, brown)= ', cos_lib)

cosine_similarity(black, brown)=  [[0.99951637]]


### 위치 인코딩

In [46]:
pe1 = aa.copy()
pe2 = aa.copy()
pe3 = aa.copy()
paa = aa.copy()
pba = ba.copy()
d_model = 512
max_print = d_model
max_length = 20

for i in range(0, max_print, 2) : 
    pe1[0][i] = math.sin(pos1 / (10000 ** ((2*i)/d_model)))
    paa[0][i] = (paa[0][i]*math.sqrt(d_model) + pe1[0][i])

    pe1[0][i+1] = math.cos(pos1 / (10000 ** ((2*i)/d_model)))
    paa[0][i+1] = (paa[0][i+1]*math.sqrt(d_model) + pe1[0][i+1])

    if dprint == 1 : 
        print(i, pe2[0][i], i+1, pe1[0][i+1])
        print(i, paa[0][i+1], i+1, paa[0][i+1])
        print('\n')

In [47]:
#위치 인코딩 벡터 : black
print('PC(black)= ', pe1)

PC(black)=  [[ 9.09297407e-01 -4.16146845e-01  9.58144367e-01 -2.86285430e-01
   9.87046242e-01 -1.60435960e-01  9.99164224e-01 -4.08766568e-02
   9.97479975e-01  7.09482506e-02  9.84703004e-01  1.74241230e-01
   9.63226616e-01  2.68690288e-01  9.35118318e-01  3.54335666e-01
   9.02130723e-01  4.31462824e-01  8.65725577e-01  5.00518918e-01
   8.27103794e-01  5.62049210e-01  7.87237823e-01  6.16649508e-01
   7.46903539e-01  6.64932430e-01  7.06710517e-01  7.07502782e-01
   6.67129099e-01  7.44942129e-01  6.28514349e-01  7.77797997e-01
   5.91127098e-01  8.06578398e-01  5.55151761e-01  8.31749082e-01
   5.20711303e-01  8.53732824e-01  4.87879932e-01  8.72910738e-01
   4.56693351e-01  8.89624178e-01  4.27157611e-01  9.04177189e-01
   3.99255812e-01  9.16839600e-01  3.72953892e-01  9.27849889e-01
   3.48205268e-01  9.37418282e-01  3.24954301e-01  9.45729733e-01
   3.03139359e-01  9.52946246e-01  2.82694966e-01  9.59209859e-01
   2.63553679e-01  9.64644730e-01  2.45647445e-01  9.69359219e-0

In [48]:
#위치 인코딩 벡터 : brown
print('PC(brown)= ', pe2)

PC(brown)=  [[-0.06562666 -0.05351061 -0.00367221  0.06062042 -0.00825019  0.03129761
   0.04094656 -0.0424781   0.02367186 -0.00713359  0.02598262 -0.00719514
  -0.00289508 -0.00929283 -0.02900256 -0.02728165  0.03671551  0.07769296
  -0.07263705 -0.04485688  0.04485427 -0.03313118  0.10418661  0.02434326
  -0.02192764  0.00515197  0.03559645  0.03915194 -0.00977631 -0.10745304
  -0.01346472  0.03907425  0.02671207 -0.01067893 -0.00663914  0.00800821
   0.04495844 -0.05629048 -0.00073539 -0.01153074 -0.08249988  0.08180326
  -0.07897271 -0.04355659  0.05569189  0.01140373 -0.00112619  0.05680707
   0.0901883   0.09711304 -0.05737246  0.04957561  0.05798693  0.10256263
  -0.06556486 -0.00416581  0.0521906  -0.04471232  0.0099958   0.05621516
   0.0546289  -0.03182605 -0.00359466  0.02774827  0.0114772  -0.0040597
  -0.03139506  0.03170055 -0.02370839 -0.02381434 -0.00193404 -0.05785833
   0.01020833 -0.07639617  0.04624535 -0.0022714   0.05824702  0.02433532
   0.00560469  0.08525062  

In [49]:
for i in range(0, max_print,2):
                pe2[0][i] = math.sin(pos2 / (10000 ** ((2 * i)/d_model)))
                pba[0][i] = (pba[0][i]*math.sqrt(d_model))+ pe2[0][i]
            
                pe2[0][i+1] = math.cos(pos2 / (10000 ** ((2 * i)/d_model)))
                pba[0][i+1] = (pba[0][i+1]*math.sqrt(d_model))+ pe2[0][i+1]
               
                if dprint==1:
                        print(i,pe2[0][i],i+1,pe2[0][i+1])
                        print(i,paa[0][i],i+1,paa[0][i+1])
                        print("\n")

print(word1,word2)
cos_lib = cosine_similarity(aa, ba)
print(cos_lib,"word similarity")
cos_lib = cosine_similarity(pe1, pe2)
print(cos_lib,"positional similarity")
cos_lib = cosine_similarity(paa, pba)
print(cos_lib,"positional encoding similarity")

if dprint == 1 : 
    print(word1)
    print('embedding')
    print(aa)
    print('positional encoding')
    print(pe1)
    print('encoded embedding')
    print(paa)

    print(word2)
    print('embedding')
    print(ba)
    print('positional encoding')
    print(pe2)
    print('encoded embedding')
    print(pba)

black brown
[[0.99951637]] word similarity
[[0.8600013]] positional similarity
[[0.9622495]] positional encoding similarity


#### 위치 인코딩 : 파이토치 사용하기

In [34]:
max_len = 20
pe = torch.zeros(max_len, d_model)
position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
pe[:, 0::2] = torch.sin(position * div_term)
pe[:, 1::2] = torch.cos(position * div_term)
#print(pe[:, 0::2])

print(pe[:,0::2])
print('\n')
print(pe[:,1::2])

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  8.2186e-01,  8.0196e-01,  ...,  1.1140e-04,
          1.0746e-04,  1.0366e-04],
        [ 9.0930e-01,  9.3641e-01,  9.5814e-01,  ...,  2.2279e-04,
          2.1492e-04,  2.0733e-04],
        ...,
        [-9.6140e-01, -6.3753e-01, -1.1153e-01,  ...,  1.8938e-03,
          1.8268e-03,  1.7623e-03],
        [-7.5099e-01, -9.9638e-01, -8.6358e-01,  ...,  2.0052e-03,
          1.9343e-03,  1.8659e-03],
        [ 1.4988e-01, -4.9773e-01, -9.2024e-01,  ...,  2.1165e-03,
          2.0418e-03,  1.9696e-03]])


tensor([[ 1.0000,  1.0000,  1.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.5403,  0.5697,  0.5974,  ...,  1.0000,  1.0000,  1.0000],
        [-0.4161, -0.3509, -0.2863,  ...,  1.0000,  1.0000,  1.0000],
        ...,
        [-0.2752, -0.7704, -0.9938,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.6603,  0.0850, -0.5042,  ...,  1.0000,  1.0000,  1.0000],
   

### 멀티-헤드 어텐션

#### 1 . 입력 표현하기

In [52]:
# 구축할 때 차원을 4개로 축소시킴
print('Step 1: Input : 3 inputs, d_model=4')
x = np.array([[1.0, 0.0, 1.0, 0.0],  # Input 1
              [0.0, 2.0, 0.0, 2.0],  # Input 2
              [1.0, 1.0, 1.0, 1.0]]) # Input 3
print(x)

Step 1: Input : 3 inputs, d_model=4
[[1. 0. 1. 0.]
 [0. 2. 0. 2.]
 [1. 1. 1. 1.]]


#### 2. 가중치 행렬 초기화

In [54]:
# 구축할 때 가중치 행렬의 차원을 3으로 축소시킴.
print('Step 2: wieghts 3 dimensions x d_model=4')
print('w_query')
w_query = np.array([[1, 0, 1],
                    [1, 0, 0],
                    [0, 0, 1],
                    [0, 1, 1]])
print(w_query)

Step 2: wieghts 3 dimensions x d_model=4
w_query
[[1 0 1]
 [1 0 0]
 [0 0 1]
 [0 1 1]]


In [ ]:
print('w_key')
w_key = np.array([[0, 0, 1],
                  [1, 1, 0],
                  [0, 1, 0],
                  [1, 1, 0]])
print(w_key)